name: hag
description: Hangi Aşı Grubundayım

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  confetti: ^0.5.4+1
  cupertino_icons: ^1.0.1
  esys_flutter_share: ^1.0.2
  flutter_hms_gms_availability: ^1.0.0
  flutter_picker:
    git: git://github.com/yangyxd/flutter_picker.git
  http: ^0.12.2
  intl: ^0.16.1
  photo_view: ^0.10.3
  screenshot: ^0.2.0
  url_launcher: ^5.7.10
  wiredash:
    git:
      url: https://github.com/wiredashio/wiredash-sdk.git
      ref: e4d5ab8574600c023c3a4e564d07c5cecb86fd5b

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.1"


flutter_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
